# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions. 

You are all required to upload this file on github before 23:59 on 1/6/2022.

#### Import NumPy as np

In [21]:
import numpy as np

#### Create an array of 10 zeros 

In [22]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [23]:
import numpy as np
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [24]:
import numpy as np
5*(np.ones(10))

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [25]:
import numpy as np
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [26]:
import numpy as np
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [27]:
import numpy as np
arr = np.arange(9)
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [29]:
np.random.rand(1)

array([0.42768001])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [30]:
np.random.randn(5,5)

array([[ 0.03178048, -0.70978693, -0.12917581, -0.19761709, -0.26355688],
       [-0.24011574,  1.32974798,  0.28486771,  0.97294082, -1.02839816],
       [ 0.0058211 , -2.48669916,  1.44353482,  0.70485576,  0.33153463],
       [ 0.1578372 ,  0.41658345,  0.98736755, -1.57613094,  0.1436936 ],
       [ 2.38204722, -0.55624847, -0.70216365, -0.16046999, -0.64091478]])

#### Create the following matrix:

#### Create an array of 20 linearly spaced points between 0 and 1:

In [32]:
np.linspace(0,1,21)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [35]:
arr = np.arange(25)
arr.reshape(5,5) + np.ones((5,5))

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

In [36]:
arr = np.arange(12)
arr = arr.reshape(3,4) + 12*np.ones((3,4))
arr

array([[12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [20., 21., 22., 23.]])

In [37]:
20

20

In [55]:
import numpy as np
arr = np.arange(2,13,5)
arr.reshape(3,1)



array([[ 2],
       [ 7],
       [12]])

In [ ]:
arr = np.arange(5)
arr = arr + 21*np.ones(5)

In [57]:
arr = np.arange(16,26,1)
print(arr.reshape(2,5))

[[16 17 18 19 20]
 [21 22 23 24 25]]


### Now do the following

#### Get the sum of all the values in mat

In [61]:
sum(arr)

205

#### Get the standard deviation of the values in mat

In [71]:
import numpy as np
np.std(arr)

2.8722813232690143

#### Get the sum of all the columns in mat

In [70]:
def colsum(arr,n,m):
    for i in range(n):
        su = 0
        for j in range (m):
            su += arr[j][i]
        print(su, end = "")
        

# Great Job!