In [1]:
import numpy as np

In [3]:
myarr = np.zeros(10)

In [4]:
myarr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
myarr1=np.ones(10)

In [6]:
myarr1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
myarr2=np.ones(10)*5

In [9]:
myarr2

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [12]:
arr=np.arange(10)

In [13]:
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr=np.linspace(10,50,41)

In [23]:
arr

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22.,
       23., 24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.,
       36., 37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47., 48.,
       49., 50.])

In [26]:
arr=np.linspace(10,50,21)

In [27]:
arr

array([10., 12., 14., 16., 18., 20., 22., 24., 26., 28., 30., 32., 34.,
       36., 38., 40., 42., 44., 46., 48., 50.])

In [28]:
arr3= np.arange(9)

In [29]:
arr3


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
arr3.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
#indexing 
ar=np.linspace(1,25,25)

In [33]:
ar

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.])

In [37]:
ar1=ar.reshape(5,5)

In [38]:
ar1

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

In [42]:
ar1[2:5,1:5]

array([[12., 13., 14., 15.],
       [17., 18., 19., 20.],
       [22., 23., 24., 25.]])

In [43]:
ar.sum()

325.0

In [44]:
np.std(ar)

7.211102550927978

In [47]:
ar1.sum(axis=0)

array([55., 60., 65., 70., 75.])