# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions. 

You are all required to upload this file on github before 23:59 on 1/6/2022.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
np.zeroes(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [7]:
np.fives(10)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [7]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [6]:
np.arange(10,52,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
arr=np.arange(0,9)
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [11]:
np.random.rand(1)

array([0.46587183])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [12]:
np.random.randn(25)

array([ 0.42412228, -0.22271243, -0.39351111,  0.78681845,  0.07629275,
       -0.90844777,  0.40602011, -1.02694383, -1.45013931, -1.48618994,
        1.16923464, -1.08730113,  0.37520874,  1.43586636,  0.90365338,
        0.93846236, -1.80924649, -1.53171941, -1.89352326, -0.07998981,
        0.15398227,  0.68268052,  0.99159703,  0.68025984, -0.06626988])

#### Create the following matrix:

In [14]:
np.arange(0,1,100)

array([0])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [15]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [17]:
arr = np.arange(1,26)
arr.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

20

array([[ 2],
       [ 7],
       [12]])

array([21, 22, 23, 24, 25])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [5]:
import numpy as np
arr = np.arange(1, 26)
arr = arr.reshape(5, 5)
array_sum = np.sum(arr)
print(array_sum)

325


#### Get the standard deviation of the values in mat

In [9]:
import numpy as np
arr = np.arange(1, 26)
arr = arr.reshape(5, 5)
std_dev = np.std(arr)
print(std_dev)

7.211102550927978


#### Get the sum of all the columns in mat

In [10]:
column_sum = np.sum(arr,axis=0)
print(column_sum)

[55 60 65 70 75]


# Great Job!