# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions. 

#### Import NumPy as np

In [2]:
import numpy as np

#### Create an array of 10 zeros 

In [3]:
array = np.zeros(10)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an array of 10 ones

In [4]:
array = np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [4]:
array = np.ones(10)*5

#### Create an array of the integers from 10 to 50

In [5]:
array = np.arange(10,51)

#### Create an array of all the even integers from 10 to 50

In [6]:
array = np.arange(10,51,2)

#### Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
array = np.arange(0,9).reshape(3,3)

#### Create a 3x3 identity matrix

In [8]:
array = np.identity(3)

#### Use NumPy to generate a random number between 0 and 1

In [17]:
array = np.random.rand()


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [3]:
array= np.random.normal(0,1,25)

#### Create the following matrix:

In [4]:
array = np.arange(0.01,1.01,0.01).reshape(10,10)

#### Create an array of 20 linearly spaced points between 0 and 1:

In [5]:
array = np.linspace(0,1,20)

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [6]:
array = np.array(([ 1,  2,  3,  4,  5],[ 6,  7,  8,  9, 10],[11, 12, 13, 14, 15],[16, 17, 18, 19, 20],[21, 22, 23, 24, 25]))

In [10]:
array[2:,0:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [9]:
array[3:4,4:]

array([[20]])

In [13]:
array[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [18]:
array[4,0:]

array([21, 22, 23, 24, 25])

In [19]:
array[3:,0:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [24]:
array.sum() 

325

#### Get the standard deviation of the values in mat

In [27]:
array.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [28]:
array.sum(axis=0)

array([55, 60, 65, 70, 75])

# Great Job!