# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions. 

#### Import NumPy as np

In [ ]:
!pip install numpy

In [1]:
import sys
import numpy as np
from numpy import random

#### Create an array of 10 zeros 

In [24]:
arr = np.empty(10, dtype=float)
for i in range(10):
  arr[i]=0.
arr  

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [25]:
arr = np.empty(10, dtype=float)
for i in range(10):
  arr[i]=1.
arr 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [26]:
arr = np.empty(10, dtype=float)
for i in range(10):
  arr[i]=5.
arr  

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [27]:
arr = np.empty(41, int)
for i in range(41):
  arr[i] = i+10
arr  

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [28]:
arr = np.empty(21, dtype=int)
for i in range(21):
  arr[i] = (2*i)+10
arr  

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [29]:
l = []
for i in range(3):
        l.append(i)
arr1 = np.array(l) 
arr2 = arr1 + 3
arr3 = arr2 + 3
arr = np.array([arr1,arr2,arr3])
arr


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [30]:
arr1 = np.empty(3, dtype=float)
for i in range(3):
    if i!=0:
        arr1[i]=0
    else: arr1[i]=1
arr2 = np.empty(3, dtype=float)
for i in range(3):
    if i!=1:
        arr2[i]=0
    else: arr2[i]=1
arr3 = np.empty(3, dtype=float)
for i in range(3):
    if i!=2:
        arr3[i]=0
    else: arr3[i]=1
arr = np.array([arr1,arr2,arr3])
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [31]:
from numpy import random
arr = np.array(random.rand(1))
arr

array([0.99422292])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [32]:
from numpy import random
arr = np.array(random.rand(25))
arr

array([0.96470254, 0.53241444, 0.46230801, 0.69023553, 0.81007297,
       0.23141839, 0.51425242, 0.08933147, 0.60503709, 0.16072991,
       0.69663441, 0.84412614, 0.66317657, 0.14224788, 0.6167639 ,
       0.3773825 , 0.40517138, 0.83890229, 0.07432983, 0.54612434,
       0.30584694, 0.37103977, 0.3539778 , 0.69477637, 0.93528341])

#### Create the following matrix:

In [33]:
arr = np.empty((10,10), float)

for j in range(10):
    l=[]
    for i in range(10):
        l.append((0.1*j)+((0.01)*i+0.01))
    arr[j] = np.array(l)
arr   


array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [34]:
arr = np.linspace(0, 1, 20)
arr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [3]:
import sys
import numpy as np
from numpy import random

In [38]:
arr = np.empty((5,5), int)

for j in range(5):
    l=[]
    for i in range(5):
        l.append((5*j)+i+1)
    arr[j] = np.array(l)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
arr[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [7]:
arr[3][4]

20

In [40]:
arr[0:3,1:2]


array([[ 2],
       [ 7],
       [12]])

In [16]:
arr[4]

array([21, 22, 23, 24, 25])

In [18]:
arr[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [21]:
mat = np.empty((5,5), int)

for j in range(5):
    l=[]
    for i in range(5):
        l.append((5*j)+i+1)
    mat[j] = np.array(l)
mat.sum()

325

#### Get the standard deviation of the values in mat

In [22]:
mat.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [23]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

# Great Job!