# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions. 

You are all required to upload this file on github before 23:59 on 1/6/2022.

#### Import NumPy as np

In [81]:
import numpy as np

#### Create an array of 10 zeros 

In [82]:
array1=np.zeros(10)
array1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [83]:
array2=np.ones(10)
array2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [84]:
array3=5*np.ones(10)
array3

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [85]:
array4=np.linspace(10,50,41)
array4

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22.,
       23., 24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.,
       36., 37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47., 48.,
       49., 50.])

#### Create an array of all the even integers from 10 to 50

In [86]:
array5=np.linspace(10,50,21)
array5

array([10., 12., 14., 16., 18., 20., 22., 24., 26., 28., 30., 32., 34.,
       36., 38., 40., 42., 44., 46., 48., 50.])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [87]:
array6=np.array([[0,1,2],[3,4,5],[6,7,8]])
array6

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [88]:
array7=np.eye(3,3)
array7

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [89]:
array8=np.random.random()
array8

0.9736991602652088

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [90]:
array9=np.random.randn(5,5) #randn fetches data from standard normal distribution #can also alter the standardisation but not now.
array9

array([[ 0.05196006, -0.1825525 ,  1.47338061, -0.26757731,  0.09197794],
       [ 0.61378191, -0.52987794,  0.96478367, -0.20487216, -1.40378471],
       [ 1.21380349,  1.3449051 ,  0.82070873, -1.25651433, -0.7423157 ],
       [-0.19619908, -2.00004266,  1.50452695,  0.20721157,  0.68543942],
       [ 1.31381577,  0.01499771, -0.80289035, -0.06709714, -0.25304879]])

#### Create the following matrix:

In [91]:
array10=np.zeros((10,10))

for i in range(10):
    for j in range(10):
        array10[i,j]=(10*i+j+1)*0.01
        j+=1
    i+=1

array10


array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [92]:
array11=np.linspace(0,1,20)
array11

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [93]:
array12=np.array([np.linspace(1,5,5),np.linspace(6,10,5),np.linspace(11,15,5),np.linspace(16,20,5),np.linspace(21,25,5)])
array12

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

In [94]:
array13=array12[2:,1:]
array13

array([[12., 13., 14., 15.],
       [17., 18., 19., 20.],
       [22., 23., 24., 25.]])

In [95]:
int(array12[3,4])


20

In [96]:
array14=array12[4:,0:]
array14

array([[21., 22., 23., 24., 25.]])

In [97]:
array15=array12[3:,0:]
array15

array([[16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

### Now do the following

#### Get the sum of all the values in mat

In [98]:
int(np.sum(array12))

325

#### Get the standard deviation of the values in mat

In [99]:
np.std(array12) #we can add ,axis=0 or ,axis=1 to get std of that axis.

7.211102550927978

#### Get the sum of all the columns in mat

In [100]:
np.sum(array12,axis=0) #axis 0 is along the column #

array([55., 60., 65., 70., 75.])

# Great Job!