# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions. 

#### Import NumPy as np

In [ ]:
import numpy as np

#### Create an array of 10 zeros 

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [ ]:
L=[]
for i in range(10):
  L.append(5)
np.array(L)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [ ]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [ ]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
arr=np.arange(0,9)
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [ ]:
np.random.rand(1)

array([0.01792413])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
np.random.randn(25)

array([ 0.13246215,  0.31546616, -1.40736426,  1.50676969, -1.93293023,
        0.22685027, -0.06625575,  1.70315155,  0.42577386,  1.56366085,
        0.01040739,  0.8910171 , -2.01015936, -1.83311602, -0.70456857,
       -1.22571699, -0.05358712, -0.94603596, -0.70694211,  0.37902071,
       -0.9539398 ,  0.43622791, -0.13309731, -1.19054185,  1.68906324])

#### Create the following matrix:

In [ ]:
arr=np.arange(0.01,1.01,0.01)
arr.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [ ]:
np.random.rand(20)

array([0.59630413, 0.3984787 , 0.76806058, 0.76976017, 0.98484962,
       0.69269666, 0.07490814, 0.58538407, 0.08039673, 0.48898864,
       0.11854679, 0.49208188, 0.59983987, 0.2807786 , 0.42537349,
       0.58592789, 0.36881893, 0.34838054, 0.2512709 , 0.46094492])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [ ]:
arr=np.arange(1,26)
arr1=arr.reshape(5,5)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
arr2=np.array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])
arr2


array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
arr1[3,4]
arr2[1,3]

20

In [ ]:

arr1[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
arr1[4]

array([21, 22, 23, 24, 25])

In [ ]:
arr1[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [ ]:
mat = np.array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
x=mat[0]+mat[1]+mat[2]+mat[3]+mat[4]
sum=0
for i in range(5):
  sum+=x[i]
sum

325

#### Get the standard deviation of the values in mat

In [ ]:
x=mat[0]+mat[1]+mat[2]+mat[3]+mat[4]
sum=0
for i in range(5):
  sum+=x[i]
mean=sum/25
temp=0
for i in range(5):
  for j in range(5):
    temp+=(mat[i][j]-mean)**2
sd=(temp/25)**0.5
sd

7.211102550927978

#### Get the sum of all the columns in mat

In [ ]:
sum=0
for i in range(5):
  sum+=mat[i]
sum

array([55, 60, 65, 70, 75])

# Great Job!