# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions. 

You are all required to upload this file on github before 23:59 on 1/6/2022.

#### Import NumPy as np

In [4]:
import numpy as np

#### Create an array of 10 zeros 

In [11]:
zeroes=np.zeros(10)
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an array of 10 ones

In [12]:
one=np.ones(10)
print(one)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 fives

In [13]:
arr=([5,5,5,5,5,5,5,5,5,5])
print(arr)

[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]


#### Create an array of the integers from 10 to 50

In [14]:
arr=np.arange(10,51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create an array of all the even integers from 10 to 50

In [17]:
arr=np.arange(10,51,2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [19]:
arr=np.arange(0,9)
p=arr.reshape(3,3)
print(p)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [20]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [23]:
a=np.random.rand(1)
print(a)

[0.2151524]


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [24]:
b=np.random.randn(5,5)
print(b)

[[ 1.11170279  1.40642976 -0.08749497 -0.61398352 -0.24195255]
 [ 1.35003554  0.99580342 -1.44624297  0.43764909  1.02806462]
 [ 0.5914075   1.40742843 -1.98950135 -0.70338254 -0.86323456]
 [-0.02480812 -0.90785105  1.18109806 -0.37265632 -0.54481069]
 [ 0.27909566  0.08094875  0.1156186  -1.44884892 -1.48130173]]


#### Create the following matrix:

In [27]:
b=np.linspace(0.01,1,100)
arr=b.reshape(10,10)
print(arr)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [28]:
c=np.linspace(0,1,20)
print(c)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [30]:
m=np.arange(1,26)
arr=m.reshape(5,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [31]:
m=arr[2:,1:]
print(m)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [32]:
m=arr[3,4]
print(m)

20


In [37]:
m=arr[:3,1]
n=m.reshape(3,1)
print(n)

[[ 2]
 [ 7]
 [12]]


In [38]:
n=arr[4,:]
print(n)

[21 22 23 24 25]


### Now do the following

#### Get the sum of all the values in mat

In [48]:
def sum_arr(arr):
    return np.sum(arr)  
np_sum = sum_arr(np.array(arr))
print(np_sum)

325


#### Get the standard deviation of the values in mat

In [50]:
def calculate_std(arr):
    flattened_arr = np.array(arr).flatten()  # Flatten the matrix to a 1D array
    std_deviation = np.std(flattened_arr)  # Calculate the standard deviation

    return std_deviation
std_dev = calculate_std(arr)
print(std_dev)

7.211102550927978


#### Get the sum of all the columns in mat

In [52]:
def sum_columns(arr):
    arr = np.array(arr)  # Convert matrix to a NumPy array
    column_sums = np.sum(arr, axis=0)  # Calculate the sum of columns along axis 0

    return column_sums


# Calculate sum of columns
column_sums = sum_columns(arr)
print("array :", column_sums)

array : [55 60 65 70 75]


# Great Job!