# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions. 

You are all required to upload this file on github before 23:59 on 1/6/2022.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [6]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [10]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [11]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [13]:
np.array([[0,1,2],[3,4,5],[6,7,8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [17]:
np.random.rand(1)

array([0.0869724])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [18]:
np.random.randn(25)

array([ 0.7729411 ,  0.55642615,  1.75468869,  1.66061136,  1.20419143,
        2.54584491, -0.94413013,  1.62830518,  0.32659225, -0.70219016,
        0.80720309,  0.32632745,  0.93805426,  0.77780233,  1.7605048 ,
       -0.66845082, -0.34917323,  0.16686801, -1.89608157,  0.10578336,
       -0.3593628 , -1.09138451, -0.75837348, -0.12600412, -1.32789197])

#### Create the following matrix:

In [19]:
np.random.randn(5,5)

array([[-0.86608858, -0.5348213 , -0.8923893 , -0.47351547, -0.46453177],
       [ 0.55086024,  0.99752168, -0.35711457,  0.75926896, -0.36868244],
       [-0.14380476, -1.5102628 ,  0.93621186,  0.89539702, -2.72825269],
       [-1.64360353, -0.59352154, -0.05525542, -2.46578933, -0.09575424],
       [-0.48746754,  0.31692416, -0.99573003,  1.42412695,  0.33988529]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [21]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

### Now do the following

#### Get the sum of all the values in mat

#### Get the standard deviation of the values in mat

#### Get the sum of all the columns in mat

# Great Job!